### ISSUE TITLE
Post Campaign giving error everytime

### ISSUE THREAD

**Issue by akatrodiya** [thorning/node-mailchimp#1]
I want to create campaign in the Mailchimp
Here is my code:

var parameters: {"recipients":{"list_id":"3c307a9f3f"},"type":"regular","settings":{"subject_line":"Your Purchase Receipt","reply_to":"orders@mammothhouse.com","from_name":"Customer Service"}}

mailchimp.post({
      path : '/campaigns',
      params: parameters
    }, function (err, result) {
      if (err) {
            console.log(err, 500);
            return;
        }
       console.log(result)
      }); 

I supplied all necessary detail but still it's giving error:

field:""
message:"Required fields were not provided: settings, type

Thank you .. can anyone help me for this?

**Comment by thorning** [comment]
The parameters you specify is body parameters. If you change `params: parameters` with `body: parameters` it should work.

I am pretty sure that mailchimps documentation used to refer to query parameters and params, but it seems they now refer to them as query parameters, and a better naming scheme for this library would be `path_params, body and query` which should avoid confusion as in this issue.

**Comment by akatrodiya** [comment]
Thankyou very very much for the quick reply.

But I already resolved the issue :-)
That is why I closed the issue.

On Wed, Jun 8, 2016 at 4:39 PM, Andreas Thorning <notifications@github.com>
wrote:

> The parameters you specify is body parameters. If you change params:
> parameters with body: parameters it should work.
>
> I am pretty sure that mailchimps documentation used to refer to query
> parameters and params, but it seems they now refer to them as query
> parameters, and a better naming scheme for this library would be path_params,
> body and query which should avoid confusion as in this issue.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/thorning/node-mailchimp/issues/1#issuecomment-224558626>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOVJH-c04mdL-YY4VWfqAOCsUSxT-cphks5qJqL7gaJpZM4Iw1T3>
> .
>



-- 
*Ajay Katrodiya*
CEO at Aarya Solution.
M - +91 9662100694
E - ajaykatrodiya@gmail.com
