### ISSUE TITLE
Capitalization of "PUT" and "GET"

### ISSUE THREAD

**Issue by tony-gutierrez** [thorning/node-mailchimp#10]
So after extensive conversation with MC, it turns out that they have a bug in batch processing, and they apparently do not plan on fixing it.  To avoid this bug, make sure you capitalize the method in batch requests (GET, PUT). 

It might be nice if this wrapper did that automagically or at least warned the user. Also this bug will only affect request routed to certain servers, so its kind of hard to track down. 

From MC:
========================================================
I checked in with our devs about the issue you reported in your previous ticket (#635981), where your lowercase 'put' calls weren't completing as expected. They directed me to the RF2616 Internet Protocol documentation -- this is expected behavior for the MailChimp API, since all HTTP method verbs must be capitalized in order for the call to be recognized.

To give you some background on this, the capitalization requirement is part of MailChimp's compliance with Internet Protocol RFCs for Request-URI's -- RFC2616 requires that these methods be case-sensitive. You can read more on this in section 5.1.1 (Page 35) of this RFC doc: https://www.w3.org/Protocols/rfc2616/rfc2616.txt

**Comment by thorning** [comment]
Thanks for the heads up. It seems like a bug that would have one pull out hair :)

It should be an easy fix, but something weird is definitely going on.

I seem to get the opposite behaviour of you: It works when my batch calls contain lower case methods, but when I uppercase them, I get a wrong operations count and malformed json back from mailchimp.

I will look closer into this asap
