### ISSUE TITLE
Requested resource could not be found

### ISSUE THREAD

**Issue by molinto** [thorning/node-mailchimp#13]
Hi, I'm following your example on adding subscribers to a list:
```
'use strict';

const Mailchimp = require('mailchimp-api-v3');
const mailchimp = new Mailchimp(API_KEY);
const listId = '12345';

mailchimp.post('/lists/'+listId, {
	email_address : 'sharry@email.com'
})
.then(function(results) {
	console.log(results);
})
.catch(function (err) {
	console.log(err);
})
```

I get the following error:
```
{ [Error: The requested resource could not be found.]
  type: 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/',
  title: 'Resource Not Found',
  status: 404,
  detail: 'The requested resource could not be found.',
  instance: '' }
```

Thanks

**Comment by thorning** [comment]
Are you trying to create a new mailing list? It seems like you are hitting the following endpoint [in the mailchimp documentation](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#create-post_lists_list_id), which is for batch posting members to an existing mailing list, and my guess it that no mailing list with id `'12345'` exist.

If the list already exists, that endpoint expects a body on the form 
```
{
  members : [{MEMBER}]
}
```
according to the documentation (I have never actually used it).
