### ISSUE TITLE
Single operations batch - query on GET not working

### ISSUE THREAD

**Issue by mwickett** [thorning/node-mailchimp#14]
I'm having issues getting responses from Mailchimp to conform to query parameters when using the "single operation" style batch call. I'm getting a response with data, but it seems like my query params aren't being sent (maybe). It's also very likely that I'm doing something wrong, but I've been looking at it carefully and can't see it. Appreciate any help. I'm working inside a Meteor app (just FYI, don't think it has any bearing here)

```
Meteor.publish('mailchimpReports', function() {
    var self = this;

    var calls = {
            method: 'GET',
            path: '/reports',
            query: {
                count: 12
            }
        }

    try {
        mailchimp.batch(calls).then((data) => {

            _.each(data[0].reports, function(report) {
                var doc = { 
                    campaign_title: report.campaign_title,
                    list_id: report.list_id,
                    list_name: report.list_name,
                    subject_line: report.subject_line,
                    emails_sent: report.emails_sent,
                    abuse_reports: report.abuse_reports,
                    unsubcribed: report.unsubcribed,
                    send_time: report.send_time,
                    bounces: report.bounces,
                    opens_total: report.opens.opens_total,
                    unique_opens: report.opens.unique_opens,
                    last_open: report.opens.last_open,
                    open_rate: report.opens.open_rate,
                    clicks_total: report.clicks.clicks_total,
                    unique_clicks: report.clicks.unique_clicks,
                    unique_subscriber_clicks: report.clicks.unique_subscriber_clicks,
                    click_rate: report.clicks.click_rate
                };
                console.log("DOC" + doc);
                self.added('reports', report.id, doc);
            });
            self.ready();
        }).catch((error) => {
            console.log("mailchimp batch error" + err);
        });
    } catch (error) {
        console.log("There was an error from mailchimp " + error);
    }
});
```

It doesn't seem to matter what I put in the `query` config (I've tried `count: 10` or `since_send_time: 2016-10-21T15:41:36+00:00` and nothing seems to change the number of responses I get.

Thank you!

**Comment by thorning** [comment]
Can you try to use `params` instead of `query`:
```
 var calls = {
            method: 'GET',
            path: '/reports',
            params: {
                count: 12
            }
        }
```
I'm pretty sure it should do it, and I'll update the library this weekend or monday to fix it.

**Comment by mwickett** [comment]
That seems to work, but there's an interesting twist. When the query (params) weren't working and I was getting max records returned (any idea what the actual batch max is? In this case I was always getting exactly 192, which seems odd), the unpacked JSON was all wrapped inside an array. Like:

```
[
  {"reports" : [
     {
          "id": "lisdjflsdkfj"
           // etc
     }
      {
          "id": "lisdjflsdkfj"
           // etc
     }
   ]
 }
]
```

So I had to iterate over report items by `each data[0].reports`

But when I used `param` instead of `query`, the unpacked results  (only 12) **weren't** inside the array.

I'm not sure if this is something to do with Mailchimp's response, or the way your module is unpacking the results at different query values. Anyways, may be nothing, but I thought it was an odd change.

**Comment by thorning** [comment]
I was unable to reproduce the behavior where a single batch operation returned an array. 
The expected behaviour is that the output matches the input, so a single response object in this case. If you see it again I would appreciate if you would open another issue on it.

I have updated the module to handle query options in the batch operations, so the original example should work again
