### ISSUE TITLE
Internal crash on empty batch queries

### ISSUE THREAD

**Issue by ovaillancourt** [thorning/node-mailchimp#15]
Hi!

Empty batch queries to Mailchimp currently result in an empty `response_body_url` field on responses (the response will be an empty string `""`). When the batch option "wait" is set to true and unwrapping is also set to true, this causes a subsequent call to `request#get` to produce an internal `request` library error. The specific call is on this line: https://github.com/thorning/node-mailchimp/blob/master/index.js#L175

It's currently pretty easy (and much smarter) to avoid all this by not making the batch call at all if the calls array is empty, but for the sake of correctness I was thinking this was something worth fixing within node-mailchimp too.

I'd gladly contribute to a pull request around this. I was wondering what the behaviour in this case should be though. My thinking was that when the batch response indicates that the status is finished, the number of submitted calls was 0, the system could resolve to an empty array immediately instead of trying to query through `request`.

Thoughts?

**Comment by thorning** [comment]
I think you are right, that when not unpacking, the response should still come from mailchimp to ensure consistent response objects.

I added the check for empty batch operations with unpack before the first request is sent to mailchimp, and return an empty array immediately. 

I think this is the most convenient solution, to avoid the often significant wait time for mailchimp to handle the batch, even if empty.
