### ISSUE TITLE
obj.trim is not a function

### ISSUE THREAD

**Issue by ivanperalta** [thorning/node-mailchimp#24]
I have the following pretty standard code

 ```
	try {
		mailchimp.get(get_url)
			.then(function(mailchimp_user) {
				// The receiver of the callback must ensure that store the id of the mailchimp response for future purposes
				console.log('User received with data %j', mailchimp_user);
				return callback(null, mailchimp_user);
			})
			.catch(function(err) {
		        console.error('Error in mailchimp::getMember %s', err.message);			
				return callback(err, null);
			});
	} catch (err) {
        console.error('Error in mailchimp::getMember %s', err.message);			
	}

```

But in my console i eventually get the following error:

obj.trim is not a function

Did you use trim without declaring inside the library?

Any advice?

**Comment by thorning** [comment]
I don't call obj.trim. One of the dependencies might.

Which version of node do you use?

Can you try to run a completely clean script, and make sure it comes from the library? Something like:
```
var Mailchimp = require('mailchimp-api-v3');
var mailchimp = new Mailchimp(api_key);

mailchimp.get('/lists')
      .then(function (result) {
        console.log(result);
      })
      .catch(function (err) {
       console.log(err);
      })
```

**Comment by ivanperalta** [comment]
I'm using 6.9.4, I'll try to identify the real cases that generate the issue and back to you as soon as I can. Thanks for the quick answer

**Comment by ivanperalta** [comment]
You're totally right the bug was out of the library, thanks for the feedback any way, and sorry for the waste of time.
