### ISSUE TITLE
Api v3 error

### ISSUE THREAD

**Issue by iLeonelPerea** [thorning/node-mailchimp#26]
Hi everyone.

I am doing a POST, trying to add a member to a List but shows the following error:

{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Missing","status":401,"detail":"Your request did not include an API key.","instance":""}

do you know what happend?

Tnks

**Comment by thorning** [comment]
did you follow the example? specifically initializing the module with an api key?
```
var Mailchimp = require('mailchimp-api-v3')

var mailchimp = new Mailchimp(api_key);
```
In any case, since the error tells you there are no API key, you need to include that part in the issue, to give readers a chance :)

**Comment by iLeonelPerea** [comment]
I am running your module in my own react code. 

I am running your example code in the terminal and it works.
But when I run it from the browser it doesn't work.

Do you think that the web browser changes the way that does the request?
Any idea?

**Comment by thorning** [comment]
How do you handle the dependencies? This module uses request to send the actual requests to mailchimp, and sets the api-key via an auth option.

**Comment by iLeonelPerea** [comment]
I am using yarn..

Also I tried different modules.

works only from the terminal. but if i run from the webbbrowser it does work

**Comment by thorning** [comment]
I added a issue for browser side support, and closing the related tasks
