### ISSUE TITLE
add isomorphic fetch maybe

### ISSUE THREAD

**Issue by nerdchacha** [thorning/node-mailchimp#27]
If you could make it isomorphic, it would be really great.

**Comment by thorning** [comment]
I have never used fetch, what would be the advantage in a library like this?

**Comment by nerdchacha** [comment]
Firstly, apologies that I haven't gone through the compile library. 
Since you are using modules like `request` (native to node), it can't be used directly on the client side (considering its called node-mailchimp). But it would be great if the same library could be used on both the browser as well as node.

**Comment by thorning** [comment]
I added a issue for browser side support, and closing the related tasks
