### ISSUE TITLE
Add Browser side support

### ISSUE THREAD

**Issue by thorning** [thorning/node-mailchimp#28]
Several issues #17 #26 #27 suggests that this library could be useful to be run in the browser, and not in node only.

I will gladly accept a pull request that facilitates this, but I do not have the time to do implement it myself in the near future.

**Comment by nerdchacha** [comment]
This might be a bummer but after a bit of research, i realized (if i am not wrong) that mailchimp APIs are not CORS enabled and thus, modifying the library to run on the browser might not server any purpose.

**Comment by thorning** [comment]
It seems you are right. Running in browser is not supported in the mailchimp api.

Setting up a proxy (with or without this library) should be fairly easy though.
