### ISSUE TITLE
Cannot make Delete request to segment

### ISSUE THREAD

**Issue by Stnlong** [thorning/node-mailchimp#32]
I'm getting an error code 400 with the message of "A Static Segment with an id of "311" does not exist for this list."

This is my code:
```
app.delete('/api/segment', (req, res) => {
  mailchimp.delete(`/lists/${list_id}/segments/${segment_id}/members/${subscriber_hash}`)
    .then(function(results){
      res.send(results);
    })
    .catch(function(err){
      res.send(err);
    });
});
```

However when I make a normal get request using the same "non-existent" segment_id used above it works.

```
app.get('/api/segment', (req, res) => {
  mailchimp.get(`/lists/${list_id}/segments/${segment_id}/members`)
    .then(function(results){
      res.send(results);
    })
    .catch(function(err){
      res.send(err);
    });
});
```

**Comment by thorning** [comment]
My best guess is that the segment is not static (a simple list of email), but dynamic and based of some user properties.
You can only delete members from a static segment.

try using the endpoint `/lists/{list_id}/segments/{segment_id}` and check the type parameter.

I don't know if it's possible to make exclude conditions on dynamic segments, but that sounds like what you are after.

**Comment by Stnlong** [comment]
That's strange. I'm following along the docs for segment members here:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/members/
 Which shows that 
DELETE /lists/{list_id}/segments/{segment_id}/members/{subscriber_hash} should be a valid endpoint

**Comment by thorning** [comment]
It only works for static segments, although it could be more clear in the documentation 

> Remove a member from the specified **static** segment.

There are three different kinds of segments `saved, static and fuzzy`, so my guess is the segment you try to delete a member from is not static.

I don't really know anything about the different types of segment, and when to use each.
