### ISSUE TITLE
Lodash vulnerability found by NSP

### ISSUE THREAD

**Issue by shierro** [thorning/node-mailchimp#39]
Hello,

Thanks for the awesome library btw!

There is a security issue found by NSP - https://github.com/nodesecurity/nsp

Details are on the screenshot. 
![screen shot 2018-05-09 at 10 09 28 am](https://user-images.githubusercontent.com/12129589/39792025-365aa7c8-5371-11e8-8b34-997d8cd59b3e.png)

Should be resolved by updating lodash. I would be happy to help & get this resolved so i'll be sending a PR soon.

Thanks!

**Comment by thorning** [comment]
Thanks for the help, I have published the new version
