### ISSUE TITLE
New typescript definitions not working

### ISSUE THREAD

**Issue by jcrobak** [thorning/node-mailchimp#42]
i'm on version 1.8.0, and the following code is working:

```
import * as MailChimp from 'mailchimp-api-v3';
...
const client = new MailChimp(apiKey);

```

With 1.9.0, I'm seeing this error on the `new MailChimp` line...

```
error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

Unfortunately, I don't know typescript definitions well enough to figure out what the problem is and why what's in #41 is working for someone else...

**Comment by thorning** [comment]
I'll take a look at it. Can you post the tsconfig.json options if you have them?

**Comment by thorning** [comment]
I have updated typings slightly, and they work for me using the import 
```import MailChimp from 'mailchimp-api-v3';```

**Comment by stevejcox** [comment]
Having the same issue. 

```error TS1192: Module '/mailchimp-api-v3/index"' has no default export.```

when using
```import MailChimp from 'mailchimp-api-v3'```

**Comment by thorning** [comment]
I think you have to run it as `import * as Mailchimp from 'mailchimp-api-v3'`, or one of those variants.

The module is still written as a javascript module, with external types. If I had extra time I would love to rewrite the module in typescript, but that will not be anytime soon.

**Comment by stevejcox** [comment]
```import * as Mailchimp from 'mailchimp-api-v3'``` is what I was using on 1.8 and it worked great, but the addition of the typings have stopped typescript from accepting it.

I don't have time to debug the typings just now, so will use 1.8 and revisit in the future.

**Comment by thorning** [comment]
I got the newest version to work with `import Mailchimp = require('mailchimp-api-v3');`
