### ISSUE TITLE
Example to subscribe a member

### ISSUE THREAD

**Issue by nuthinking** [thorning/node-mailchimp#43]
I guess it would be a pretty important example to show, including check if the member is already registered etc. For instance as the check of the member could return a 404 I am not sure a clean chain is possible with promises.

**Comment by thorning** [comment]
I will definitely welcome pull requests with more examples.

For chains including checking existence, you need to handle errors. The main ways to do this depend on how you use promises. .catch, async/await with try/catch or .then(success, error) should all be possible.

Finally, for this usecase, you should properly use the "add or update" endpoint: [http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#%20](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#%20)
