### ISSUE TITLE
Issue with consecutive requests

### ISSUE THREAD

**Issue by chris-divvito** [thorning/node-mailchimp#48]
Hi,

We've had the same code running for a long period of time using this wrapper, and as of yesterday morning we've encountered an intermittent issue when consecutive requests make updates to a user.

I'm fairly certain this is an issue on Mailchimp's end, but I'm wondering if anyone else has encountered and found a good workaround for this issue.

Essentially we have a process that runs on Google Cloud Functions which, in response to a certain request, makes an update on the user. it may also, later in the process, make another update to the user, although through the magic of Promises we can be certain that the first request has completed when this occurs.

an MCVE of this problem is as follows: 

```
import * as expressLogging from 'express-logging';
import * as express from 'express';
import * as cookieParser from 'cookie-parser';
import * as functions from "firebase-functions";
import * as Mailchimp from 'mailchimp-api-v3';

const request = require('request');

const cors = require('cors')({origin: true});
const testing = express();

testing.use(cors);
testing.use(cookieParser());
testing.use(expressLogging(console));

const mailchimp = new Mailchimp('AN-API-KEY');
const listId = 'A-LIST-ID';
const emailHash = 'AN-EMAIL-HASH';

function getPost() {
  return new Promise((resolve, reject) => {
    request.patch('https://jsonplaceholder.typicode.com/posts/1', {
      json: JSON.stringify({title: 'title'}),
      headers: {
        "Content-type": "application/json; charset=UTF-8"
      }
    }, (err, resp) => {
      if (err) {
        reject();
      } else {
        resolve();
      }
    });
  })
}

testing.get('/hello', (req, res) => {
  console.log('Testing begins');
  getPost().then(() => {
    console.log('Testing Complete');
    res.send('Hello');
  }).catch(() => {
    res.send('Oh No');
  });
});

testing.get('/helloMulti', (req, res) => {
  console.log('Testing begins');
  getPost()
    .then(getPost)
    .then(getPost)
    .then(getPost)
    .then(getPost)
    .then(getPost)
    .then(() => {
      console.log('Testing Complete');
      res.send('Hello');
    })
    .catch(() => {
      res.send('Oh No');
    });
});

function randomizeName() {
  const FNAME = 'chris+' + Math.floor(Math.random() * 1000);

  return mailchimp.patch(
    `/lists/${listId}/members/${emailHash}`,
    {merge_fields: {FNAME}}
  ).then(() => {
    console.log('randomized name');
  });
}

testing.get('/helloMailchimp', (req, res) => {
  console.log('Testing begins');
  randomizeName().then(() => {
    console.log('Testing complete');
    res.send('Hello');
  }).catch(() => {
    res.send('Oh no')
  });
});

testing.get('/helloMailchimpMulti', (req, res) => {
  console.log('Testing begins');
  randomizeName()
    .then(randomizeName)
    .then(randomizeName)
    .then(() => {
      console.log('Testing complete');
      res.send('Hello');
    })
    .catch(() => {
      res.send('Oh no')
    });
});

export default functions.https.onRequest(testing);
```

`/hello` and `/helloMailchimp` work fine, as does `/helloMulti`. `/helloMultiMailchimp` fails maybe one in 3-5 times. When it fails, the first request appears to be serviced in <1 second, and the next one never does - GCF cloud functions times out after 60 seconds of waiting for it.

I'm waiting on a response from Mailchimp API support, and trying to find a good way to restructure the actual implementation to use a batch request in the meantime, but is this something anyone else has encountered and/or solved?

**Comment by thorning** [comment]
It does indeed sound like something outside the library. Depending on what is needed, a batch request might help.
