### ISSUE TITLE
Delete method returns 204 status code 

### ISSUE THREAD

**Issue by michaloo** [thorning/node-mailchimp#5]
When I do a query to remove an user from static segment in a Mailchimp List, the Mailchimp API responds with a 204 status code and "No Content" message:

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/members/#delete-delete_lists_list_id_segments_segment_id_members_subscriber_hash

On the following line the library checks whether the response code was 200, if not it it tries to get `details` param of the body.
https://github.com/thorning/node-mailchimp/blob/master/index.js#L469

In the delete case the body is empty and it causes `TypeError: Cannot read property 'detail' of undefined` error.

The 204 No Content response is valid and no error should be triggered in this case.

**Comment by dottodot** [comment]
I'm seeing the same issue too.

**Comment by thorning** [comment]
Thanks for the report, I will update the library tonight to handle all successcodes correctly
