### ISSUE TITLE
[question] Can I use the wrapper for sending multiple emails?

### ISSUE THREAD

**Issue by ovvn** [thorning/node-mailchimp#50]
Sorry, I'm new to mailchimp's api, didn't find an example of how to send a message to multiple email addresses.  Can I do something like this:
```
var Mailchimp = require('mailchimp-api-v3')
var mailchimp = new Mailchimp(api_key);
mailchimp('/messages/send', {
    message: {
        to: [{email: 'git@jimsc.com', name: 'Jim Rubenstein'}],
        from_email: 'you@domain.com',
        subject: "Hey, what's up?",
        text: "Hello, I sent this message using mailchimp."
    }
}, function(error, response)
{
    //uh oh, there was an error
    if (error) console.log( JSON.stringify(error) );

    //everything's good, lets see what mailchimp said
    else console.log(response);
});
```

**Comment by thorning** [comment]
That is not really Mailchimps core functionality (and I think not possible at all). What you are properly looking for is a transactional email service.

Mailgun, Mandrill, Sendgrid are names I've heard in that context, but don't know much else about - so your own research is needed :)

**Comment by ovvn** [comment]
@thorning thanks
