### ISSUE TITLE
Allow for subscriber language support

### ISSUE THREAD

**Issue by abennouna** [thorning/node-mailchimp#52]
Thanks for this wrapper. It just works!

Currently, when adding a new member to a list, Mailchimp API v3 uses the `language` property only as a management preference.

If we want Mailchimp to send the **Opt-in confirmation email** in the subscriber’s language, we have to use the `Accept-Language` header (as found in https://stackoverflow.com/a/22072474 and https://github.com/drewm/mailchimp-api/issues/148).

If you like that feature, I can submit a PR.

**Comment by thorning** [comment]
I would welcome a PR for this. 

I think the best way to do it, is to add a optional header to options, and merge it when sending the request to mail chimp.

**Comment by thorning** [comment]
Thanks for the PR, I added a comment on why language is handled and published it to npm
