### ISSUE TITLE
Your merge fields were invalid & Limit not working.

### ISSUE THREAD

**Issue by digipigeon** [thorning/node-mailchimp#61]
Apologies for the poor ticket content, but not really sure whats going wrong.

At about 13th Sept our Sync script stopped working (was working for many months before).

2 notable changes:
1. Only 1000 records are being received despite
```await mailchimp.get({ path: '/lists/XXX/members', query: {count: 3000}});```

2. I am now getting `Your merge fields were invalid.` Despite the code not changing
```await mailchimp.post({ path : '/lists/xxx/members', body: { email_address: email, status: 'subscribed' }})```

I have also tried updating the lib to the latest version, changing nodejs versions and installing afresh in a new project.

Any help debugging would be much appreciated.

**Comment by thorning** [comment]
maybe the list changed, requiring certain merge fields? It sounds like a problem with the mailchimp list or on thier side of the api.

For the get request, you could try to do a single request in a batch, like in the example in the read me. Mailchimp might have a upper limit on their counts.

**Comment by digipigeon** [comment]
Hello thorning,

Yes you were correct, there was a merge field, I had to debug the package as this error was not available. Thank you.

However even with batch:
`await mailchimp.batch({ method : 'get', path: '/lists/XXX/members', query: {count: 3000}});`
never returns more than 1000

**Comment by digipigeon** [comment]
Achieved with:
```
	var allMembers = []
	do {
		var {members} = await mailchimp.get({ path: '/lists/XXX/members'}, {offset: allMembers.length, count: 1000});
		allMembers.push(...members)
	} while (members.length === 1000)
```

**Comment by thorning** [comment]
Seems mailchimp might have introduced an upper limit, even in batch calls. 

Another approach that might or might not be better, would be to get the total count, then construct all the calls with offsets and call them at once in a single batch call.
