### ISSUE TITLE
members put

### ISSUE THREAD

**Issue by Karman40** [thorning/node-mailchimp#62]
My error:
`Error: karman.zsombor@elitit.hu is already a list member. Use PUT to insert or update list members.`

```
  md5.appendStr(email);
  const md5Hash = md5.end();
  const path = `/lists/46afa54add/members/${md5Hash}`;
  return await mailchimp.put(path, {
    email_address : email,
    status : 'subscribed'
  });
```

Am I stupid or is this bad?

**Comment by its-VSP** [comment]
@Karman40 , clearly it is saying `karman.zsombor@elitit.hu` is already a list member.
So you should not send the email in request body again as mentioned [here](https://mailchimp.com/developer/reference/lists/list-members/#put_/lists/-list_id-/members/-subscriber_hash-) in docs

**Comment by Karman40** [comment]
Request Body Parameters:
email_address* => required

How do I know if he is on the list or not? The point of this would be if it has an update on it, if not it will add it.

**Comment by Karman40** [comment]
Nowhere does he say that if he is on the list then I should not put it in the body.

**Comment by its-VSP** [comment]
@Karman40 ., it is mentioned like
>Email address for a subscriber. This value is required only if the email address is not already present on the list.

**Comment by Karman40** [comment]
@its-VSP 
This is crap.

` return await mailchimp.get(path);` If not on the list I get an error.

`  return await mailchimp.put(path, {
    email_address: email,
    status: 'subscribed'
  });
`
If the list is already bugged, I get an error.

So what's the good solution? ... I can't write it, I can't query it ... So what's the point of it all, if you keep throwing mistakes?

**Comment by its-VSP** [comment]
@Karman40 
 As i can see there is not update to repo from July, suggest you to use the API directly.

**Comment by its-VSP** [comment]
Lemme know if you face any challenges in hitting direct MailChimp API

**Comment by thorning** [comment]
This sounds like a problem/design decision of the Mailchimp API itself.
